apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment  
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels: 
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: husainm/nodehelloworld:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3000